# This file may be used to create an environment using:
# $ conda env create -f <this file>
# platform: osx-64
name: nupic.torch
channels:
  - defaults

dependencies:
  - python=3.8
  - pip

  - pip:
      # Install nupic.torch in develop mode
      - -e .[dev]

